### ISSUE TITLE
[FEATURE]: Task List

### ISSUE THREAD

**Issue by AmyNicole8715** [rainbow-passage/rainbow-station#21]
**User story - describe how the feature should work.**
As a user I should be able to click on my task list modal in the dashboard or the corresponding icon in the sidebar and go to a page where I can see all available tasks to be completed. Even if a task is for a different team I should be able to see it unless it is marked for limited access, this way if I am done with all of my tasks I can see what other teams need help and potentially pitch in there as well. If I am a coordinator or supervisor I should be able to easily add tasks by beginning to type when focused on the task list page, initiation of typing will popup a modal that includes the name of the task, the details for it, my id, name, and position as the coordinator, assignees if I know who will be doing it, the option to add opt in if it isn't for someone specific (this should be default), limited access checkbox (checked by default), status, frequency, reset time (TTL before it needs done again), both enter and tab should move to the next field

**Feature list**
List all of the individual features/subfeatures this solution should implement:
- [ ] Task list sortable by column
- [ ] Creation upon click or typing
- [ ] Access Management
- [ ] Detailed Coordinator information (what department, who, best contact)
- [ ] Task list fields navigate on Return/Tab
- [ ] Shift Tab goes back a field 
- [ ] Task Status
- [ ] Task Assignees
- [ ] Task Frequency by dropdown
- [ ] Task TTL by custom between 1 day (86000 secs) and 1 week (604800 seconds)
- [ ] Task Details should allow for rich text 
- [ ] Task Details should allow for 2000 characters
- [ ] Option to opt into a task

**Design/screenshots**
Add any visuals you've created or found that would help show what this feature should ultimately look like
